param(
    [string]$SourceDir = "..\dist",
    [string]$ExeName = "SecureSFTPClient.exe",
    [string]$IconName = "..\logo.ico",
    [string]$DefaultInstallDir = "$env:ProgramFiles\SecureSFTPClient"
)

function Assert-Admin {
    $current = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($current)
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        Write-Host "Restarting elevated..."
        Start-Process -FilePath powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"" -Verb RunAs
        exit
    }
}

Assert-Admin

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$source = (Resolve-Path (Join-Path $scriptDir $SourceDir)).ProviderPath
$exePath = Join-Path $source $ExeName
$iconPath = (Resolve-Path (Join-Path $scriptDir $IconName)).ProviderPath

if (-not (Test-Path $exePath)) {
    Write-Error "Executable not found: $exePath"
    exit 1
}

$installDir = Read-Host "Install directory (press Enter to accept default: $DefaultInstallDir)"`
if ([string]::IsNullOrWhiteSpace($installDir)) { $installDir = $DefaultInstallDir }

Write-Host "Installing to: $installDir"

# Create install dir
New-Item -Path $installDir -ItemType Directory -Force | Out-Null

# Copy files
Copy-Item -Path $exePath -Destination $installDir -Force
Copy-Item -Path $iconPath -Destination $installDir -Force

# Create Start Menu shortcut
$shell = New-Object -ComObject WScript.Shell
$folder = [Environment]::GetFolderPath('Programs')
$startMenuFolder = Join-Path $folder 'Secure SFTP Client'
New-Item -ItemType Directory -Path $startMenuFolder -Force | Out-Null
$shortcutPath = Join-Path $startMenuFolder 'Secure SFTP Client.lnk'
$sc = $shell.CreateShortcut($shortcutPath)
$sc.TargetPath = Join-Path $installDir $ExeName
$sc.IconLocation = Join-Path $installDir 'logo.ico'
$sc.WorkingDirectory = $installDir
$sc.Save()

# Create Desktop shortcut for current user
$desktop = [Environment]::GetFolderPath('Desktop')
$desktopShortcut = Join-Path $desktop 'Secure SFTP Client.lnk'
$sc2 = $shell.CreateShortcut($desktopShortcut)
$sc2.TargetPath = Join-Path $installDir $ExeName
$sc2.IconLocation = Join-Path $installDir 'logo.ico'
$sc2.WorkingDirectory = $installDir
$sc2.Save()

# Create Uninstall script
$uninstallScript = Join-Path $installDir 'Uninstall.ps1'
@"
# Uninstall script generated by installer
param(
    [switch]
    `\$Silent
)

if (-not ( [Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host 'Please run this script as administrator.'
    exit 1
}

Write-Host 'Uninstalling Secure SFTP Client...'
Stop-Process -Name SecureSFTPClient -ErrorAction SilentlyContinue
Remove-Item -Path `"$installDir\*`" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path `"$installDir`" -Force -ErrorAction SilentlyContinue

# Remove shortcuts
Remove-Item -Path `"$shortcutPath`" -Force -ErrorAction SilentlyContinue
Remove-Item -Path `"$desktopShortcut`" -Force -ErrorAction SilentlyContinue

# Remove registry uninstall entry
Remove-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\SecureSFTPClient" -Recurse -ErrorAction SilentlyContinue

Write-Host 'Uninstall complete.'
"@ | Out-File -FilePath $uninstallScript -Encoding UTF8

# Register uninstall entry in registry
$uninstallKey = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\SecureSFTPClient'
New-Item -Path $uninstallKey -Force | Out-Null
Set-ItemProperty -Path $uninstallKey -Name 'DisplayName' -Value 'Secure SFTP Client'
Set-ItemProperty -Path $uninstallKey -Name 'DisplayVersion' -Value '1.0.0'
Set-ItemProperty -Path $uninstallKey -Name 'Publisher' -Value 'You'
Set-ItemProperty -Path $uninstallKey -Name 'InstallLocation' -Value $installDir
Set-ItemProperty -Path $uninstallKey -Name 'UninstallString' -Value ("powershell -NoProfile -ExecutionPolicy Bypass -File `"$uninstallScript`"")

Write-Host "Installation complete. Shortcuts created."
Write-Host "Installed to: $installDir"
Write-Host "To uninstall, run: powershell -NoProfile -ExecutionPolicy Bypass -File `"$uninstallScript`""