param(
    [string]$SourceDir = "..\dist",
    [string]$ExeName = "SecureSFTPClient.exe",
    [string]$IconName = "..\logo.ico",
    [string]$DefaultInstallDir = "$env:USERPROFILE\AppData\Local\SecureSFTPClientTest"
)

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$source = (Resolve-Path (Join-Path $scriptDir $SourceDir)).ProviderPath
$exePath = Join-Path $source $ExeName
$iconPath = (Resolve-Path (Join-Path $scriptDir $IconName)).ProviderPath

if (-not (Test-Path $exePath)) {
    Write-Error "Executable not found: $exePath"
    exit 1
}

$installDir = Read-Host "Install directory (press Enter to accept default: $DefaultInstallDir)"
if ([string]::IsNullOrWhiteSpace($installDir)) { $installDir = $DefaultInstallDir }

Write-Host "Installing to: $installDir"

New-Item -Path $installDir -ItemType Directory -Force | Out-Null
Copy-Item -Path $exePath -Destination $installDir -Force
Copy-Item -Path $iconPath -Destination $installDir -Force

$shell = New-Object -ComObject WScript.Shell
$folder = [Environment]::GetFolderPath('Programs')
$startMenuFolder = Join-Path $folder 'Secure SFTP Client Test'
New-Item -ItemType Directory -Path $startMenuFolder -Force | Out-Null
$shortcutPath = Join-Path $startMenuFolder 'Secure SFTP Client Test.lnk'
$sc = $shell.CreateShortcut($shortcutPath)
$sc.TargetPath = Join-Path $installDir $ExeName
$sc.IconLocation = Join-Path $installDir 'logo.ico'
$sc.WorkingDirectory = $installDir
$sc.Save()

$desktop = [Environment]::GetFolderPath('Desktop')
$desktopShortcut = Join-Path $desktop 'Secure SFTP Client Test.lnk'
$sc2 = $shell.CreateShortcut($desktopShortcut)
$sc2.TargetPath = Join-Path $installDir $ExeName
$sc2.IconLocation = Join-Path $installDir 'logo.ico'
$sc2.WorkingDirectory = $installDir
$sc2.Save()

$uninstallScript = Join-Path $installDir 'Uninstall.ps1'
@"
# Uninstall script generated by installer
param(
    [switch]$Silent
)

Write-Host 'Uninstalling Secure SFTP Client Test...'
Stop-Process -Name SecureSFTPClient -ErrorAction SilentlyContinue
Remove-Item -Path `"$installDir\*`" -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item -Path `"$installDir`" -Force -ErrorAction SilentlyContinue
Remove-Item -Path `"$shortcutPath`" -Force -ErrorAction SilentlyContinue
Remove-Item -Path `"$desktopShortcut`" -Force -ErrorAction SilentlyContinue
Write-Host 'Uninstall complete.'
"@ | Out-File -FilePath $uninstallScript -Encoding UTF8

Write-Host "Installation complete. Shortcuts created."
Write-Host "Installed to: $installDir"
Write-Host "To uninstall, run: powershell -NoProfile -ExecutionPolicy Bypass -File `"$uninstallScript`""